# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_aaa <- function(model_, y_, pars_, s0_, x_) {
    .Call(`_tsets_filter_aaa`, model_, y_, pars_, s0_, x_)
}

filter_mmm <- function(model_, y_, pars_, s0_, x_) {
    .Call(`_tsets_filter_mmm`, model_, y_, pars_, s0_, x_)
}

filter_mam <- function(model_, y_, pars_, s0_, x_) {
    .Call(`_tsets_filter_mam`, model_, y_, pars_, s0_, x_)
}

filter_powermam <- function(model_, y_, pars_, s0_, x_) {
    .Call(`_tsets_filter_powermam`, model_, y_, pars_, s0_, x_)
}

simulate_aaa <- function(model_, e_, pars_, s0_, x_) {
    .Call(`_tsets_simulate_aaa`, model_, e_, pars_, s0_, x_)
}

simulate_mmm <- function(model_, e_, pars_, s0_, x_) {
    .Call(`_tsets_simulate_mmm`, model_, e_, pars_, s0_, x_)
}

simulate_mam <- function(model_, e_, pars_, s0_, x_) {
    .Call(`_tsets_simulate_mam`, model_, e_, pars_, s0_, x_)
}

simulate_powermam <- function(model_, e_, pars_, s0_, x_) {
    .Call(`_tsets_simulate_powermam`, model_, e_, pars_, s0_, x_)
}

